"""Add claimed_by to FoodPost

Revision ID: 2bb54df539a3
Revises: 
Create Date: 2025-09-25 08:13:14.315325

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2bb54df539a3'
down_revision = None
branch_labels = None
depends_on = None

def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('food_post', schema=None) as batch_op:
        batch_op.add_column(sa.Column('claimed_by', sa.Integer(), nullable=True))
        batch_op.create_foreign_key(
            'fk_foodpost_claimed_by',   # explicit name
            'user',                     # target table
            ['claimed_by'],             # local column
            ['id']                      # target column
        )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('food_post', schema=None) as batch_op:
        batch_op.drop_constraint('fk_foodpost_claimed_by', type_='foreignkey')
        batch_op.drop_column('claimed_by')
    # ### end Alembic commands ###
